export const SERVICES = [
  { id: 'haircut', en: 'Haircut & style', es: 'Corte y peinado', cat: 'Hair' },
  { id: 'color', en: 'Color & balayage', es: 'Color y balayage', cat: 'Hair' },
  { id: 'blowout', en: 'Blowout', es: 'Secado', cat: 'Hair' },
  { id: 'barber', en: 'Barber cut & beard', es: 'Corte de barbero', cat: 'Barber' },
  { id: 'mani', en: 'Manicure', es: 'Manicura', cat: 'Nails' },
  { id: 'pedi', en: 'Pedicure', es: 'Pedicura', cat: 'Nails' },
  { id: 'gel', en: 'Gel & acrylics', es: 'Gel y acrílicas', cat: 'Nails' },
  { id: 'lashes', en: 'Lash extensions', es: 'Pestañas', cat: 'Lashes' },
  { id: 'brows', en: 'Brow shape & tint', es: 'Cejas', cat: 'Lashes' },
  { id: 'facial', en: 'Facial', es: 'Facial', cat: 'Skin' },
  { id: 'massage', en: 'Massage', es: 'Masaje', cat: 'Body' },
  { id: 'botox', en: 'Botox & fillers', es: 'Botox y rellenos', cat: 'Med spa' },
];

export const BIDS = [
  {
    id: 'b1', lat: 26.1948, lon: -98.1836, name: 'Casa de Belleza', neighborhood: 'Pharr', distance: 0.8,
    rating: 4.9, reviews: 312, price: 95, originalPrice: 135,
    responseMin: 4, badges: ['licensed', 'top'], mood: 0, categories: ['hair'],
    note_en: 'We can fit you in today at 4pm. Includes wash + blow dry.',
    note_es: '¡Tenemos espacio hoy a las 4pm! Incluye lavado y secado.',
    artist: 'Marisol R.', years: 12, lang: 'EN/ES',
    slot_en: 'Today, 4:00 PM', slot_es: 'Hoy, 4:00 PM',
  },
  {
    id: 'b2', lat: 26.2034, lon: -98.2300, name: 'Studio Onyx', neighborhood: 'McAllen', distance: 2.1,
    rating: 4.8, reviews: 189, price: 145, originalPrice: 180,
    responseMin: 11, badges: ['licensed'], mood: 3, categories: ['hair', 'lashes'],
    note_en: 'Premium products, private chairs. First-time client gets a free deep condition.',
    note_es: 'Productos premium, sillas privadas. Cliente nuevo recibe tratamiento gratis.',
    artist: 'Diego A.', years: 8, lang: 'EN',
    slot_en: 'Tomorrow, 10:30 AM', slot_es: 'Mañana, 10:30 AM',
  },
  {
    id: 'b3', lat: 26.3017, lon: -98.1633, name: 'La Reina Salon', neighborhood: 'Edinburg', distance: 1.4,
    rating: 5.0, reviews: 87, price: 78, originalPrice: 110,
    responseMin: 2, badges: ['new', 'top'], mood: 5, categories: ['hair', 'nails'],
    note_en: 'New on Glossi! 30% off this week to introduce ourselves to neighbors.',
    note_es: '¡Nuevas en Glossi! 30% de descuento esta semana.',
    artist: 'Luz G.', years: 6, lang: 'EN/ES',
    slot_en: 'Today, 6:15 PM', slot_es: 'Hoy, 6:15 PM',
  },
  {
    id: 'b4', lat: 26.2159, lon: -98.3253, name: 'The Beauty Loft', neighborhood: 'Mission', distance: 3.7,
    rating: 4.7, reviews: 421, price: 165, originalPrice: 195,
    responseMin: 24, badges: ['licensed', 'verified'], mood: 1, categories: ['hair', 'skin'],
    note_en: 'Senior stylist with 15+ years color experience. Loyalty rewards available.',
    note_es: 'Estilista senior con 15+ años en color.',
    artist: 'Ana V.', years: 17, lang: 'EN/ES',
    slot_en: 'Saturday, 11:00 AM', slot_es: 'Sábado, 11:00 AM',
  },
  {
    id: 'b5', lat: 26.1595, lon: -97.9908, name: 'Brisa Hair Bar', neighborhood: 'Weslaco', distance: 5.2,
    rating: 4.6, reviews: 142, price: 110, originalPrice: 140,
    responseMin: 38, badges: ['verified'], mood: 4, categories: ['hair', 'barber'],
    note_en: 'Bilingual stylists. Free parking. Walk-ins on weekdays.',
    note_es: 'Estilistas bilingües. Estacionamiento gratis.',
    artist: 'Carmen P.', years: 9, lang: 'EN/ES',
    slot_en: 'Today, 7:45 PM', slot_es: 'Hoy, 7:45 PM',
  },
];

export const GUIDES = [
  { kicker_en: 'GUIDE · 6 MIN', kicker_es: 'GUÍA · 6 MIN', t_en: 'How to talk about color in Spanglish', t_es: 'Cómo hablar de color en spanglish', mood: 5 },
  { kicker_en: 'RGV PICKS · 4 MIN', kicker_es: 'EL VALLE · 4 MIN', t_en: 'Six neighborhood salons we love this month', t_es: 'Seis salones del barrio que amamos', mood: 0 },
  { kicker_en: 'PRICING · 3 MIN', kicker_es: 'PRECIOS · 3 MIN', t_en: 'What a fair price looks like in the Valley', t_es: 'Qué es un precio justo en el Valle', mood: 4 },
];

export const REQUESTS = [
  { id: 'r1', name: 'Sofia M.', initials: 'SM', service: 'Color & balayage', service_es: 'Color y balayage', when: 'ASAP · Today/tomorrow', when_es: 'YA · Hoy o mañana', distance: 0.8, posted: '2 min', note: 'Shoulder-length, dark brown. Want soft caramel balayage, low-maintenance.', note_es: 'Largo a hombros, castaño oscuro. Balayage caramelo suave.', bidsCount: 1, urgent: true, photos: 2, customerOffer: 85 },
  { id: 'r2', name: 'Daniela R.', initials: 'DR', service: 'Lash · Hybrid set', service_es: 'Pestañas · Híbridas', when: 'This week', when_es: 'Esta semana', distance: 1.4, posted: '14 min', note: 'Hybrid set, natural look, first-time. Allergy to standard adhesive.', note_es: 'Híbridas naturales, primera vez. Alergia al adhesivo común.', bidsCount: 4, urgent: false, photos: 3 },
  { id: 'r3', name: 'Maritza C.', initials: 'MC', service: 'Gel mani + pedi', service_es: 'Gel mani + pedi', when: 'Saturday', when_es: 'Sábado', distance: 2.1, posted: '38 min', note: 'Wedding guest Sunday. Soft nude or blush.', note_es: 'Invitada a boda el domingo. Nude o rosa.', bidsCount: 6, urgent: false, photos: 1 },
  { id: 'r4', name: 'Kevin O.', initials: 'KO', service: 'Barber + beard', service_es: 'Corte de barbero', when: 'Today after 5pm', when_es: 'Hoy después de 5pm', distance: 3.2, posted: '1 hr', note: 'Skin fade, beard line-up. Last cut went too short on top.', note_es: 'Skin fade, línea de barba. Último corte muy corto.', bidsCount: 2, urgent: true, photos: 2 },
];

export const T = {
  en: {
    greeting: 'Good afternoon,', user: 'Sofia',
    heroLine1: 'Real prices,', heroLine2: 'real fast.',
    heroSub: 'Tell salons what you want. They send prices. You pick.',
    cta: 'Post a request', livePulse: 'salons online in 78501',
    findingSalons: 'Finding nearby salons', bidsRolling: 'Bids rolling in',
    yourRequest: 'Your request', color: 'Color & balayage',
    today: 'Today', tomorrow: 'Tomorrow', flexible: "I'm flexible",
    asap: 'ASAP', thisWeek: 'This week', when: 'When?',
    detail: 'Add details', detailPh: 'Length, your usual color, things to avoid…',
    photos: 'Add reference photos', photosOpt: 'Optional · helps salons quote accurately',
    yourZip: 'Your ZIP', send: 'Send to nearby salons',
    sendSub: 'Free · No commitment · Bids in 5–15 min',
    bidsTitle: 'Bids', bidsSub: n => `${n} salons sent prices`,
    sortPrice: 'Price', sortRating: 'Rating', sortFastest: 'Closest', sortSoonest: 'Soonest',
    book: 'Book this', minAgo: 'min ago', miAway: 'mi', yrs: 'yrs',
    youSave: 'You save',
    booked: 'Booked', bookedSub: 'Confirmation sent. See you soon.',
    addCal: 'Add to calendar', directions: 'Directions',
    nearby: 'Salons near you', editorial: 'The Glossi Field Guide',
    editorialSub: 'Texas beauty, by neighborhood',
    home: 'Home', explore: 'Explore', quotes: 'Quotes', inbox: 'Inbox', me: 'Me',
    nextSlot: 'Next opening',
  },
  es: {
    greeting: 'Buenas tardes,', user: 'Sofia',
    heroLine1: 'Precios reales,', heroLine2: 'al instante.',
    heroSub: 'Dile a los salones qué quieres. Te envían precios. Tú eliges.',
    cta: 'Publicar solicitud', livePulse: 'salones activos en 78501',
    findingSalons: 'Buscando salones cerca', bidsRolling: 'Llegando ofertas',
    yourRequest: 'Tu solicitud', color: 'Color y balayage',
    today: 'Hoy', tomorrow: 'Mañana', flexible: 'Soy flexible',
    asap: 'Lo antes posible', thisWeek: 'Esta semana', when: '¿Cuándo?',
    detail: 'Detalles', detailPh: 'Largo, tu color habitual, qué evitar…',
    photos: 'Fotos de referencia', photosOpt: 'Opcional · ayuda a cotizar mejor',
    yourZip: 'Tu CP', send: 'Enviar a salones cercanos',
    sendSub: 'Gratis · Sin compromiso · Ofertas en 5–15 min',
    bidsTitle: 'Ofertas', bidsSub: n => `${n} salones enviaron precios`,
    sortPrice: 'Precio', sortRating: 'Reseñas', sortFastest: 'Cercanía', sortSoonest: 'Más pronto',
    book: 'Reservar', minAgo: 'min', miAway: 'mi', yrs: 'años',
    youSave: 'Ahorras',
    booked: 'Reservado', bookedSub: 'Confirmación enviada. ¡Te esperamos!',
    addCal: 'Agregar al calendario', directions: 'Cómo llegar',
    nearby: 'Salones cercanos', editorial: 'La Guía Glossi',
    editorialSub: 'Belleza de Texas, por colonia',
    home: 'Inicio', explore: 'Explorar', quotes: 'Ofertas', inbox: 'Mensajes', me: 'Yo',
    nextSlot: 'Próximo turno',
  },
};
